config/routes.rb
Pythoncampus::Application.routes.draw do
  devise_for :users

  match 'home' => 'home#index'
  match 'under_construction' => 'home#under_construction'
  match 'local' => 'home#map'
  match 'equipe' => 'home#team'
  match 'contato' => 'home#contact'
  match 'send_contact' => 'home#send_contact'

  resources :presentations, :only => :index
  match 'programacao' => 'presentations#index'

  resources :attendees, :only => [:new, :create]
  match 'inscricao' => 'attendees#new'

  resources :registrations, :only => [:index, :show, :destroy] do
    collection do
      get :request_confirm
      post :confirm
    end
  end

  root :to => 'home#index'

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  has_many :registrations
  has_many :presentations, :through => :registrations

  validates_presence_of :name, :email
  validates_format_of :email,
                      :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/,
                      :allow_blank => true
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  has_and_belongs_to_many :speakers
  has_many :registrations
  has_many :attendees, :through => :registrations

  MAXIMUM_CAPACITY = 20

  def short_course?
    kind.try(:capitalize) == "Minicurso"
  end

  def self.short_courses
    all.select(&:short_course?)
  end

  def description
    "#{title} - #{speakers.map(&:name).join(', ')}"
  end

  def confirmed_registrations
    registrations.select(&:confirmed?)
  end

  def self.available_short_courses
    short_courses.reject(&:crowded?)
  end

  def crowded?
    confirmed_registrations.count >= MAXIMUM_CAPACITY
  end
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :attendee
  belongs_to :presentation

  def description
    "#{attendee.name} - #{presentation.title}"
  end

  def confirmed?
    confirmed_at.present?
  end

  def confirm
    self.confirmed_at = Time.now
  end

  def confirm!
    confirm
    save!
  end

  def self.available_for_confirmation
    all.reject(&:confirmed?).reject {|r| r.presentation.crowded? }
  end
end

app/models/speaker.rb
require 'digest'

class Speaker < ActiveRecord::Base
  has_attached_file :photo

  def twitter_link
    return nil if twitter.blank?
    twitter =~ /^\@?(.+)$/
    "http://twitter.com/#{$1}"
  end

  def github_link
    return nil if github.blank?
    "https://github.com/#{github}"
  end

  def photo_link
    return photo.url if photo.exists?
    gravatar_link
  end

  private

  def gravatar_link
    return nil if email.blank?
    "http://gravatar.com/avatar.php?gravatar_id=#{Digest::MD5.hexdigest email}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attendees_controller.rb
class AttendeesController < InheritedResources:: Base
  def create
    @attendee = Attendee.new(params[:attendee])
    if @attendee.save
      presentation = Presentation.find(params['short_course'])
      @attendee.registrations.create! :presentation => presentation
      AttendeeMailer.pre_registration_email(@attendee).deliver
      render :template => 'attendees/show'
    else
      @short_course = params['short_course']
      render :action => 'new'
    end
  end
end

app/controllers/home_controller.rb
require 'open-uri'

class HomeController < ApplicationController
  def index
  end

  def under_construction
  end

  def map
  end

  def team
    scrapper = NsiMemberScrapper.new(open("#{NsiMemberScrapper::NSI_SITE}/membros"))
    @content, @members_css_link = scrapper.content, scrapper.members_css_link
  end

  def contact
    @contact = Contact.new
  end

  def send_contact
    @contact = Contact.new(params[:contact])
    if @contact.valid?
      AttendeeMailer.contact_email(@contact).deliver
      redirect_to root_path
      flash[:notice] = 'Contato realizado com sucesso'
    else
      render :action => :contact
    end
  end
end

class Contact < ActiveModelForm
  attr_accessor :name, :email, :subject, :message
  validates_presence_of :name, :email, :subject, :message
end

app/controllers/presentations_controller.rb
class PresentationsController < InheritedResources::Base
end

app/controllers/registrations_controller.rb
# coding: utf-8

class RegistrationsController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def request_confirm
    @registrations = Registration.available_for_confirmation.sort_by(&:description)
  end

  def confirm
    @new_registrations = params[:registrations].map {|id| Registration.find(id) }
    @new_registrations.each do |registration|
      registration.confirm!
      AttendeeMailer.confirm_registration_email(registration).deliver
    end
    render :action => :index
  end

  def destroy
    Registration.find(params[:id]).delete
    flash[:notice] = 'Inscrição excluída com sucesso'
    redirect_to :action => :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendees/new.html.slim
h1 Inscrição

= semantic_form_for @attendee do |form|
  = form.input :name, :label => 'Nome'
  = form.input :email, :label => 'E-mail'
  li
    = label_tag :short_course, 'Minicurso'
    = select_tag :short_course, options_from_collection_for_select(Presentation.available_short_courses, :id, :description, @short_course)
  p.warning
    | Todos os minicursos, exceto "Linux Básico", têm como pré-requisito conhecimentos básicos de Linux (terminal/editor de texto).
  = form.submit 'Inscrever'

app/views/attendees/show.html.erb
<h1>Pré-inscrição</h1>

<p><%= @attendee.name %> (<%= @attendee.email %>), você acaba de realizar sua pré-inscrição no minicurso
<em><%= @attendee.presentations.map(&:title).sort.join(', ').sub(/(.*)\,\ /, '\1 e ') %></em>.</p>

<p>Seu código de inscrição é <%= @attendee.id %>.</p>

<p>Não se esqueça de levar o alimento até o NSI para confirmar a sua inscrição.
Você receberá um e-mail com maiores instruções a respeito da entrega do
alimento.</p>

<p><strong>A organização da PythOnCampus IFF 2011 agradece o seu
interesse!</strong></p>

app/views/home/contact.html.slim
h1 Fale com a gente

= semantic_form_for @contact, :url => { :action => :send_contact }, :html => { :method => :post } do |form|
  = form.input :name, :label => 'Nome'
  = form.input :email, :label => 'E-mail'
  = form.input :subject, :label => 'Assunto'
  = form.input :message, :as => :text, :label => 'Mensagem', :input_html => { :cols => 65, :rows => 8 }
  = form.submit 'Enviar'

app/views/home/index.html.erb
<h1>O que é?</h1>
<p>
    <strong>PythOnCampus</strong> é uma caravana de tecnologia que visita as universidades integrando estudantes ao mercado.
    Este é o evento que mostra que é possível transformar a paixão por tecnologia em uma carreira de sucesso.
    O evento é <strong>gratuito</strong> e aberto ao público em geral.<br /> Fonte: <a href="http://pythoncampus.org" title="pythoncampus.org">pythoncampus.org</a>
</p>

<h1>Onde e Quando?</h1>
<p>
    O <strong>NSI (Núcleo de Pesquisa em Sistemas de Informação)</strong> trará a caravana PythonCampus para o
    <strong>Instituto Federal Fluminense Campus Campos-Centro</strong>, no dia <strong>16 de setembro de 2011</strong> (sexta-feira)
    das <strong>8:00 às 22:00</strong>.
</p>

<h1>O que teremos?</h1>
<p>
    Durante o evento teremos minicursos, palestras, coding dojo e muito mais, além de uma grande oportunidade para <i>networking.</i><br />
    <strong>Confira a <%= link_to 'programação', programacao_path %> para maiores detalhes.</strong>
</p>

app/views/home/map.html.erb
<% content_for :additional_scripts do %>
  <%= javascript_include_tag 'map', 'http://maps.google.com/maps/api/js?sensor=false&language=pt-BR' %>
<% end %>

<h1>Localização do IFF (Antigo CEFET-Campos)</h1>

<div id='address_info'>
  Rua Dr. Siqueira, 273 - Parque Dom Bosco - Campos dos Goytacazes, RJ - CEP 28030-130<br/>
  Tel: (22) 2726-2800 - Fax: (22) 2733-3079
</div>

<div id="map_div" class="map_div"></div>

app/views/home/team.html.erb
<% content_for :additional_scripts do %>
  <%= stylesheet_link_tag @members_css_link, 'team' %>
<% end %>

<h1>Equipe do NSI</h1>

<%=raw @content %>

app/views/home/under_construction.html.erb
<h1>Em construção</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PythOnCampus IFF 2011</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, 'jquery' %>
  <%= yield :additional_scripts %>
  <%= yield :additional_styles %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="cabecalho">
    <div id="logo">
      <a href="/">
        <%= image_tag 'logo.png', :alt => 'PythOnCampus IFF', :title => 'PythOnCampus IFF' %>
      </a>
    </div>

    <div id="navegacao">
      <ul>
        <li><%= link_to 'Início', root_path %></li>
        <li><%= link_to 'Programação', programacao_path %></li>
        <li><%= link_to 'Inscrição', inscricao_path %></li>
        <li><%= link_to 'Local', local_path %></li>
        <li><%= link_to 'Contato', contato_path %></li>
        <li><%= link_to 'Equipe', equipe_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to '-Confirmar-', request_confirm_registrations_path %></li>
          <li><%= link_to '-Ver-', registrations_path %></li>
        <% end %>
        <li>
      </ul>
    </div>
  </div>
  <div id='conteudo'>
    <div id='notice'>
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </div>

  <div id="rodape">
    <div id="links_rodape">
      <a href="http://nsi.iff.edu.br">NSI - Núcleo de Pesquisa em Sistemas de Informação</a><br/>
      <a href="http://www.iff.edu.br">Instituto Federal Fluminense</a>
    </div>
  </div>
</body>
</html>

app/views/presentations/index.html.erb
<h1>Programação</h1>

<div id="programacao">
  <% @presentations.each do |presentation| %>
    <div class="atividade">
      <div class="cabecalho">
        <%= presentation.kind %> - <%= presentation.title %> <span><%= presentation.time %></span>
      </div>
      <div class="dados">
        <%= presentation.summary %><br/>
        Local: <strong><%= presentation.room %></strong>
        <% presentation.speakers.each do |speaker| %>
          <div class="responsavel">
            <div class="foto">
              <%= image_tag speaker.photo_link || "", :title => speaker.name, :alt => "" %>
            </div>
            <div class="descricao">
              <strong><%= speaker.name %></strong>
              <br/>
              <%= speaker.summary %><br/>
              Organização: <strong><%= speaker.organization %></strong>
            </div>
            <div class="site">
              <% if speaker.twitter_link.present? %>
                <a href='<%= speaker.twitter_link %>'>
                  <%= image_tag 'twitter.png', :alt => 'Twitter', :title => 'Twitter' %>
                </a>
              <% end %>
              <% if speaker.github_link.present? %>
                <a href='<%= speaker.github_link %>'>
                  <%= image_tag 'github.png', :alt => 'Github', :title => 'github' %>
                </a>
              <% end %>
              <% if speaker.site.present? %>
                <a href='<%= speaker.site %>'>
                  <%= image_tag 'site.png', :alt => 'Site/Blog', :title => 'Site/Blog' %>
                </a>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>